version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
